<script src="{{ asset('files') }}/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="{{ asset('files') }}/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('files') }}/assets/pages/data-table/js/jszip.min.js"></script>
<script src="{{ asset('files') }}/assets/pages/data-table/js/pdfmake.min.js"></script>
<script src="{{ asset('files') }}/assets/pages/data-table/js/vfs_fonts.js"></script>
<script src="{{ asset('files') }}/bower_components/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="{{ asset('files') }}/bower_components/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="{{ asset('files') }}/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('files') }}/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ asset('files') }}/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
<!-- Custom js -->
<script src="{{ asset('files') }}/assets/pages/data-table/js/data-table-custom.js"></script>
